### ISSUE TITLE
Difference between docstring and implementation Matern 12

### ISSUE THREAD

**Issue by vdutor** [thomaspinder/GPJax#118]
Hi all, 

I noticed a difference between the implementation and the docstring of the Matern 1/2 kernel, namely the factor `0.5`:
https://github.com/thomaspinder/GPJax/blob/246addfd9089b1fd8d694ab2193366a61230c113/gpjax/kernels.py#L185
https://github.com/thomaspinder/GPJax/blob/246addfd9089b1fd8d694ab2193366a61230c113/gpjax/kernels.py#L196

For reference, GPflow and GPyTorch don't seem to add the additional factor:
- https://github.com/GPflow/GPflow/blob/ee8dd4dc611152ab5ac72a534348b81f05a4193c/gpflow/kernels/stationaries.py#L205
- https://github.com/cornellius-gp/gpytorch/blob/master/gpytorch/kernels/matern_kernel.py#L100

I apologise for the nitpicky nature of this issue, but it would be nice to have these definitions be consistent across packages :)

Thanks,
Vincent

**Comment by thomaspinder** [comment]
Thanks for catching this @vdutor. This has now been resolved.
