### ISSUE TITLE
bug: Simple example can not work

### ISSUE THREAD

**Issue by pczzy** [thomaspinder/GPJax#141]
# Bug Report
predictive_distribution = likelihood(params, latent_distribution)
params does not define

**GPJax version:**
0.5.0 

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Comment by thomaspinder** [comment]
Thanks for raising this @pczzy - this should be resolved now.
